### PR TITLE
Dropdown enhancements and improvements

### PR DESCRIPTION
**Pull request by busheikin**
# Link to Github Issue

#349 #350 #351 

# Description
- Enhancement: Ability to add contextual text to a dropdown option
- Enhancement: Accessibility via keyboard navigation
- Enhancement: Multiple menu sizes
- Improvement to vertical spacing
- Improvement to disabled-related css

### CODE REVIEW

**Comment by ZainW** [comment]
is the no divider between options ok? also will need some doc improvements and fix failing CI. If I'm the one working on this it will need to wait

**Comment by busheikin** [comment]
Dividers will be placed between specific options to section off longer dropdowns when appropriate

**Comment by Boshes** [comment]
something weird with the css syntax cause circle to break

**Comment by busheikin** [comment]
maybe it doesn't like `cursor`? I notice my VScode isn't coloring it like a normal property but I don't know why, afaik it's valid.

**Comment by Boshes** [comment]
I guess the linter settings are more strict, it `yarn lint:css` doesn't like commented code

**Comment by busheikin** [comment]
@Boshes ohhh. Should I remove?

**Comment by Boshes** [comment]
probably unfortunately

**Comment by busheikin** [comment]
@Boshes i think this syntax will be accepted

**Comment by Boshes** [comment]
Looks good can squash

**Comment by busheikin** [comment]
squished

**Pull request merged**
