### PR TITLE
ao-multi-select component

### PR DESCRIPTION
**Pull request by sarngru**
# Link to Github Issue
https://github.com/AmpleOrganics/Blaze.vue/issues/331

# Description
A multi select component

multi-select

### CODE REVIEW

**Comment by ZainW** [comment]
checkboxes look out of line with their accompanying labels
disabled still allows it to be clicked and select/deselect options
disabled all still allows things to be selected and deselected
selections is off centered vertically

**Comment by sarngru** [comment]
> checkboxes look out of line with their accompanying labels
> disabled still allows it to be clicked and select/deselect options
> disabled all still allows things to be selected and deselected
> selections is off centered vertically

@ZainW these issues have been addressed. please review again.

**Comment by ZainW** [comment]
the summary text is off centered,

could you please add 
```css
align-items: center;
```
to `ao-multi-select__summary`. this will center the selection and placeholder

**Comment by ZainW** [comment]
otherwise it looks good and i'll approve

**Comment by sarngru** [comment]
> the summary text is off centered,
> 
> could you please add
> 
> ```css
> align-items: center;
> ```
> 
> to `ao-multi-select__summary`. this will center the selection and placeholder

done

**Comment by ZainW** [comment]
@sarngru please run yarn on this and commit the result. make sure you are on the latest yarn of 1.16.0

**Comment by sarngru** [comment]
> @sarngru please run yarn on this and commit the result. make sure you are on the latest yarn of 1.16.0

done

**Comment by tessakruger** [comment]
Very nice!! 👏

**Pull request merged**
